import { Child } from './childInfo';

export let childlist: Child[] = [
  {
    id: 1,
    name: "Ева",
    patronym: "Михайловна",
    surname: "Котова",
    birthDate: "05-03-2005",
    gender: "girl",
    needSum: 9308407,
    donatSum: 8875000,
    history: "История пока не добавлена...",
},
{
    id: 2,
    name: "Дамир",
    patronym: "Артёмович",
    surname: "Скворцов",
    birthDate: "10-16-2011",
    gender: "boy",
    needSum: 7223978,
    donatSum: 5924901,
    history: "История пока не добавлена...",
},
{
    id: 3,
    name: "Анна",
    patronym: "Андреевна",
    surname: "Герасимова",
    birthDate: "03-23-2020",
    gender: "girl",
    needSum: 520190,
    donatSum: 412955,
    history: "История пока не добавлена...",
},
{
    id: 4,
    name: "Богдан",
    patronym: "Леонидович",
    surname: "Крюков",
    birthDate: "09-24-2007",
    gender: "boy",
    needSum: 1260711,
    donatSum: 902054,
    history: "История пока не добавлена...",
},
{
    id: 5,
    name: "Кирилл",
    patronym: "Дмитриевич",
    surname: "Денисов ",
    birthDate: "12-13-2016",
    gender: "boy",
    needSum: 3153460,
    donatSum: 2223351,
    history: "История пока не добавлена...",
}
];


  /*{
    id: 1,
    surname: "...",
    name: "...",
    patronym: "...",
    needSym: 150000,
    donatSym: 82500,
  },
  {
    id: 2,
    surname: "....",
    name: "....",
    patronym: "....",
    needSym: 1500000,
    donatSym: 500000,
  },
  {
    id: 3,
    surname: "....!",
    name: "....!",
    patronym: "....!",
    needSym: 150000000,
    donatSym: 148000000,
  },
  {
    id: 4,
    surname: "....!!",
    name: "....!!",
    patronym: "....!!",
    needSym: 48000000,
    donatSym: 59000,
  },
  {
    id: 5,
    surname: "....!!!",
    name: "....!!!",
    patronym: "....!!!",
    needSym: 85000000,
    donatSym: 3000,
  },*/