import { Child } from './childInfo';

export let childlist: Child[] = [
  {
    id: 1,
    name: "Ева",
    patronym: "Михайловна",
    surname: "Котова",
    birthDate: "05-03-2005",
    gender: "girl",
    needSum: 9308407,
    donatSum: 8875000,
    history: "История пока не добавлена...",
},
{
    id: 2,
    name: "Дамир",
    patronym: "Артёмович",
    surname: "Скворцов",
    birthDate: "10-16-2011",
    gender: "boy",
    needSum: 7223978,
    donatSum: 5924901,
    history: "История пока не добавлена...",
},
{
    id: 3,
    name: "Анна",
    patronym: "Андреевна",
    surname: "Герасимова",
    birthDate: "03-23-2020",
    gender: "girl",
    needSum: 520190,
    donatSum: 412955,
    history: "История пока не добавлена...",
},
{
    id: 4,
    name: "Богдан",
    patronym: "Леонидович",
    surname: "Крюков",
    birthDate: "09-24-2007",
    gender: "boy",
    needSum: 1260711,
    donatSum: 902054,
    history: "История пока не добавлена...",
},
{
    id: 5,
    name: "Кирилл",
    patronym: "Дмитриевич",
    surname: "Денисов ",
    birthDate: "12-13-2016",
    gender: "boy",
    needSum: 3153460,
    donatSum: 2223351,
    history: "История пока не добавлена...",
}
];